[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Molecular Dynamics", "children": [
        {"tag": "protocol_group", "text": "System preparation", "openItem": "False", "children": [
            {"tag": "protocol", "value": "AmberSystemPrep", "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "MD simulation", "openItem": "False", "children": [
            {"tag": "protocol", "value": "AmberMDSimulation", "text": "default"}
        ]},
        {"tag": "protocol_group", "text": "Simulation analysis", "openItem": "False", "children": [
            {"tag": "protocol", "value": "AmberModifySystem", "text": "default"}
	    ]}
	]}
]