[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Molecular Dynamics", "children": [
        {"tag": "protocol", "value": "AmberSystemPrep", "text": "amber - system preparation"},
        {"tag": "protocol", "value": "AmberMDSimulation", "text": "amber - MD simulation"},
        {"tag": "protocol", "value": "AmberLigandPrep", "text": "amber - ligand preparation"}
	]}
	]

