[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Molecular Dynamics", "children": [
        {"tag": "protocol", "value": "AmberSystemPrep", "text": "amber - system preparation"},
        {"tag": "protocol", "value": "AmberMDSimulation", "text": "amber - run MD simulation"},
        {"tag": "protocol", "value": "AmberModifySystem", "text": "amber - system modification"}
	]}
	]

